FROM amazoncorretto:21-alpine-jdk

ARG JAR_FILE=./build/libs/*.jar
COPY ${JAR_FILE} server.jar

EXPOSE 8080

ENTRYPOINT ["java", "-Xms256m", "-Xmx512m", "-Dspring.profiles.active=dev", "-jar", "server.jar"]