FROM amazoncorretto:21-alpine-jdk

ARG JAR_FILE=./build/libs/*.jar
COPY ${JAR_FILE} server.jar

EXPOSE 8080

ENTRYPOINT ["java", "-Xms256m", "-Xmx512m", "-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=/tmp/heapdump.hprof", "-XX:OnOutOfMemoryError=kill -9 %p", "-Dspring.profiles.active=prod", "-jar", "server.jar"]
