spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

  profiles:
    active: stage

jwt:
  secret: ${{secrets.JWT_SECRET}}

auth:
  free-apis:
    ${{secrets.FREE_API_LIST}}
  admin-apis:
    ${{secrets.ADMIN_API_LIST}}
  admin:
    secret:
      ${{secrets.ADMIN_SECRET}}

server:
  port: ${{secrets.SERVER_PORT}}
