name: Test on Pull Request

on:
  pull_request:
    branches:
      [ "dev", "main" ]p

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: set up redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: 6

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "firebase-key.json"
          json: ${{ secrets.FIREBASE_KEY }}

      - name: Move firebase-key.json to src/main/resources
        run: |
          mkdir -p ./src/main/resources
          mv firebase-key.json ./src/main/resources/firebase-key.json
        shell: bash

      - name: Test with Gradle
        run: |
          ./gradlew test

      - name: Report Test Result
        uses: mikepenz/action-junit-report@v3
        if: failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}
